---
- hosts: all
  sudo: yes
  tasks:
    - name: install packages on Debian/Ubuntu
      apt: name={{ item }} state=present
      with_items:
        - cmake
        - curl
        - gawk
        - git
        - python-dev
        - python-pip
        - screen
        - sysstat
        - tcpdump
        - vim
        - zsh
      when: ansible_os_family == 'Debian'

- hosts: all
  sudo: no
  tasks:
    - name: install packages on Mac OS X
      homebrew: name={{ item }} state=present
      with_items:
        - cmake
        - gawk
        - git
        - python
      ignore_errors: yes
      when: ansible_os_family == 'Darwin'
