---
- hosts: all
  sudo: yes
  tasks:
    - name: install packages on Debian/Ubuntu
      apt: name={{ item }} state=present
      with_items:
        - acpi
        - acpica-tools
        - acpitool
        - autoconf
        - autocutsel
        - automake
        - autotools-dev
        - avahi-daemon
        - bash-completion
        - bc
        - bison
        - blueman
        - bluetooth
        - bluez
        - bridge-utils
        - build-essential
        - busybox
        - bzip2
        - ca-certificates
        - clang
        - clusterssh
        - cmake
        - cmake
        - cpp
        - cpufrequtils
        - cups
        - curl
        - curl
        - daemontools
        - debootstrap
        - desktop-base
        - devscripts
        - dnsmasq
        - dput
        - dropbox
        - ebtables
        - encfs
        - evince
        - exuberant-ctags
        - fakeroot
        - ffmpeg
        - file
        - firmware-iwlwifi
        - firmware-linux-free
        - flashplugin-nonfree
        - flex
        - fontconfig
        - fontconfig-config
        - fonts-crosextra-caladea
        - fonts-crosextra-carlito
        - fonts-dejavu
        - fonts-dejavu-core
        - fonts-dejavu-extra
        - fonts-droid-fallback
        - fonts-freefont-ttf
        - fonts-inconsolata
        - fonts-lato
        - fonts-liberation
        - fonts-linuxlibertine
        - fonts-lmodern
        - fonts-lyx
        - fonts-noto-mono
        - fonts-opensymbol
        - fonts-sil-gentium
        - fonts-sil-gentium-basic
        - fonts-texgyre
        - fonts-vlgothic
        - fonts-wine
        - ftp
        - fuse
        - fuse2fs
        - g++
        - gawk
        - gawk
        - gcc
        - gccgo
        - gcc-multilib
        - gdb
        - ghc
        - ghc-doc
        - ghostscript
        - gimp
        - git
        - git
        - git-man
        - git-svn
        - g++-multilib
        - gnupg
        - golang
        - golang-doc
        - grep
        - groff-base
        - gthumb
        - gzip
        - htop
        - iftop
        - imagemagick
        - info
        - iotop
        - iproute
        - iproute2
        - ipset
        - iptables
        - iptables-dev
        - iw
        - jq
        - laptop-detect
        - less
        - libreoffice
        - lightdm
        - lshw
        - lsof
        - m4
        - make
        - makedev
        - man-db
        - manpages
        - manpages-dev
        - manpages-posix
        - manpages-posix-dev
        - mawk
        - mcelog
        - mplayer
        - netcat6
        - netcat-openbsd
        - netcat-traditional
        - network-manager
        - nfs-common
        - nfs-kernel-server
        - nmap
        - openssh-client
        - openssh-server
        - openssh-sftp-server
        - openssl
        - openvpn
        - p7zip-full
        - pandoc
        - parcellite
        - parted
        - passwd
        - pasystray
        - patch
        - patchutils
        - pavucontrol
        - pkg-config
        - pm-utils
        - pulseaudio
        - pulseaudio-module-bluetooth
        - pulseaudio-utils
        - puppet-lint
        - pwgen
        - python
        - python-all
        - python-all-dev
        - python-dev
        - python-dev
        - python-pip
        - qemu-kvm
        - qemu-system-common
        - qemu-system-x86
        - qemu-utils
        - rdesktop
        - redis-server
        - redis-tools
        - remmina
        - rfkill
        - rsync
        - sbuild
        - schroot
        - schroot-common
        - screen
        - screen
        - scrot
        - sed
        - socat
        - speedometer
        - sqlite3
        - sshfs
        - sshpass
        - ssl-cert
        - strace
        - sudo
        - sysstat
        - tar
        - tcpdump
        - tmux
        - traceroute
        - trayer
        - tree
        - ttf-bitstream-vera
        - ttf-dejavu
        - ttf-liberation
        - tzdata
        - ubuntu-archive-keyring
        - ubuntu-dev-tools
        - unrar
        - unzip
        - util-linux
        - vagrant
        - valgrind
        - vim
        - vim
        - virtualbox
        - virtualbox-dkms
        - virtualbox-guest-additions-iso
        - virtualbox-qt
        - virtualenv
        - vlc
        - vpnc-scripts
        - wget
        - wireshark
        - xclip
        - xmobar
        - xmonad
        - xorg
        - xterm
        - xtightvncviewer
        - zip
        - zsh
      when: ansible_os_family == 'Debian'

- hosts: all
  sudo: no
  tasks:
    - name: install packages on Mac OS X
      homebrew: name={{ item }} state=present
      with_items:
        - cmake
        - gawk
        - git
        - python
      ignore_errors: yes
      when: ansible_os_family == 'Darwin'
