---
# ansible-playbook -c local -i localhost, dotfiles.yml
- hosts: all
  sudo: no

  vars:
    homedir: "{{ ansible_env.HOME }}"

  tasks:
    - name: create base directory
      file: path={{ homedir }} state=directory mode=0755

    - name: check files/directories in dotfiles/
      local_action: shell find dotfiles -maxdepth 1|grep -v '^dotfiles$'
      register: dotfiles

    - name: copy dotfiles
      synchronize: src={{ item }}
                   dest={{ homedir }}/
                   archive=yes
                   delete=yes
      with_items: "{{ dotfiles.stdout.split('\n') }}"

    - name: create .local directory
      file: path={{ homedir }}/.local state=directory mode=0755

    - name: copy local/* to {{ homedir }}/.local/
      synchronize: src=local/
                   dest={{ homedir }}/.local/
                   archive=yes
                   delete=no

    - name: remove dotfiles.yml
      file: path={{ homedir }}/dotfiles.yml state=absent

    - name: create .terminfo directory
      file: path={{ homedir }}/.terminfo state=directory mode=0755

    - name: copy terminfo files
      copy: src={{ item }} dest={{ homedir }}/.terminfo/
      with_fileglob:
        - terminfo/*.terminfo

    - name: compile terminfo
      shell: tic {{ item }}
      with_fileglob:
        - "{{ homedir }}/.terminfo/*.terminfo"

    - name: finish YCM installation
      shell: ./install.sh --clang-completer
      args:
        chdir: "{{ homedir }}/.vim/bundle/YouCompleteMe"
