---
- hosts: all
  sudo: yes

  tasks:
    - name: update /etc/locale.gen
      lineinfile:
        dest: /etc/locale.gen
        line: "{{ item }}"
      with_items:
        - en_US.UTF-8 UTF-8
        - hu_HU.UTF-8 UTF-8

    - name: generate locals
      command: locale-gen

    - name: change shell to bash
      command: /usr/bin/chsh -s /bin/bash {{ ansible_env.SUDO_USER }}

    - name: remounting existing filesystems with noatime
      mount: src={{item.device}}
             name={{item.mount}}
             fstype={{item.fstype}}
             opts={{item.options}},noatime
             state=present
      when: "{{ item.mount in ['/', '/boot'] and 'noatime' not in item.options }}"
      with_items: "{{ ansible_mounts }}"

    - name: run fstrim daily
      cron: name="run fstrim daily"
            special_time=daily
            job="fstrim /"

    - name: set swappiness
      sysctl: name=vm.swappiness
              value=1
              state=present
              sysctl_file=/etc/sysctl.conf

    - name: add kernel parameters to grub
      lineinfile: dest=/etc/default/grub
                  regexp="^GRUB_CMDLINE_LINUX="
                  line="GRUB_CMDLINE_LINUX=\"cgroup_enable=memory swapaccount=1 elevator=noop\""
      register: grub_cmdline

    - name: run update-grub if /etc/default/grub has changed
      command: update-grub
      when: grub_cmdline | changed

    - name: make backlight sysfs file writable
      copy: dest=/etc/udev/rules.d/97-intel_backlight.rules
            mode=0644
            owner=root
            group=root
            content='KERNEL=="intel_backlight", SUBSYSTEM=="backlight", RUN+="/bin/chmod 0666 /sys/class/backlight/%k/brightness"'
